[package]
name = "wk-predictions"
version = "0.1.0"
authors = ["Joeri Samson <joerisamson@gmail.com>"]

[dependencies]
diesel = { version = "1.2.1", features = ["postgres"] }
diesel-derive-enum = { version = "0.4", features = ["postgres"] }
dotenv = "0.9.0"
