[package]
name = "wk-predictions"
version = "0.1.0"
authors = ["Joeri Samson <joerisamson@gmail.com>"]

[dependencies]
diesel = { version = "1.1.1", features = ["postgres"] }
diesel_infer_schema = { version = "1.1.0", features = ["postgres"] }
dotenv = "0.9.0"
iron = "0.6.0"
